### PR TITLE
Dependency update

### LINKED ISSUE #65: Lodash in deps have security issue - need to upgrade lodash version
More info: https://snyk.io/vuln/npm:lodash:20180130

How to fix: Upgrade lodash to version 4.17.5 or higher.

### PR DESCRIPTION
**Pull request by Berkmann18**
I updated some dependencies after getting vulnerability warnings in a project dependent on this one (read more here: https://github.com/Berkmann18/nodemailer-sendgrid-transport/commit/1a7c367a41431ce5c30a68686e80910946c04abd) as well as added ISSUE_TEMPLATE (with some core elements) and USE_CASE.md (with one use case so far).
Fixes #65 
Closes #64 
# Fixes # 

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### Short description of what this PR does:
- Updated dependencies that were flagged as unmet and/or vulnerable.
- Added files required to pass 2 tests.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by Berkmann18** [comment]
The failing tests are docker related (2x, so not my area (yet)) and one regarding `./TROUBLESHOOTING.md` which I have no idea how to go about in regards to this package.

**Comment by thinkingserious** [comment]
Thanks for the update @Berkmann18!

**Comment by Berkmann18** [comment]
You're welcome @thinkingserious.

**Comment by Berkmann18** [comment]
Is there any plans on merging this PR along with others I've seen?

**Comment by thinkingserious** [comment]
Hello @Berkmann18,

The plan is to move this repo [here](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages), but so far that has not bubbled up on our backlog.

Is that something you would be interested in helping with?

Thanks!

With Best Regards,

Elmer

**Comment by Berkmann18** [comment]
@thinkingserious I wouldn't mind helping with that.

**Comment by thinkingserious** [comment]
Awesome @Berkmann18! 

Please let me know how I can help. 

I think the first step would be to create a branch and add a nodemailer-sendgrid-transport folder here: https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages

**Comment by Berkmann18** [comment]
Okay, I will do that and try to follow the structure that the other directories have in that folder.

**Comment by Berkmann18** [comment]
Since the `sendgrid` package is deprecated and that the [`sendgrid-transport.js`](https://github.com/Berkmann18/sendgrid-nodejs/blob/transport/packages/nodemailer-sendgrid-transport/src/sendgrid-transport.js) uses it, I was wondering if I should use `../mail/index` or `../client/index` but both (even when not including `index`) make `npm test` fail.

How can I go about resolving that?

**Comment by thinkingserious** [comment]
Hi @Berkmann18,

Yes, we should update the code to use the latest version of the SDK, which is now [@sendgrid/mail](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/mail).

**Comment by Berkmann18** [comment]
Okay, I managed to move `nodemailer-sendgrid-transport` to the new location while refactoring it so it would match the structure and style that the other packages use; the problem is the same, whenever I run `npm test` on the repo it outputs this (using the codebase from [this commit](https://github.com/Berkmann18/sendgrid-nodejs/commit/56d24faab262bd9c963de052322cdfadf7536a25):

```bash
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'sendgrid'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/packages/contact-importer/src/importer.spec.js:9:54)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/istanbul/lib/hook.js:107:24)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/babel-register/lib/node.js:152:7)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at runFn (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:52:16
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:361:13
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:52:16
    at done (/home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:246:17)
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:44:16
    at /home/maxie/Dropbox/Contribs/sendgrid-nodejs/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1539:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
I tried twicking things and tracing where the issue was exactly but I can't seem to find.
I suppose the update you mentioned would impact this so should I wait until it's done then submit a PR to the `sendgrid-nodejs` repo?

**Comment by thinkingserious** [comment]
Ah, it looks like the `contact-importer` package still relies on the old `sendgrid` package. You may just want to go ahead and install the `sendgrid` package on your system for testin purposes. Or, you can just submit your PR and I can help fix the tests.

**Comment by Berkmann18** [comment]
I tried installing it but it requires to rename the package to something different which then lead to a series of issues around js files in packages with `require('@sendgrid/...')` and some API changes as well as some apparently missing dependency such as `deepmerge` in `@sendgrid/helpers`.
So I'll go ahead and submit the PR.

**Pull request closed without merging**
