### PR TITLE
populate cc/ccname and bcc/bccname

### PR DESCRIPTION
**Pull request by yye0528**
add cc and bcc support

### CODE REVIEW

**Comment by davidtsuji** [comment]
is there an eta on when/if this will be merged?

**Comment by eddiezane** [comment]
Thanks for the PR! This doesn't quite work yet though. 

I'll try and allocate some time soon, but you're welcome to dig deeper if you find the time.

**Comment by mderazon** [comment]
This seems to work for me.

@eddiezane  What steps did you try that it didn't work for you ?

**Comment by eddiezane** [comment]
Thanks for the PR! Just merged #13. We need to figure out the ccname and bccname still.

**Pull request closed without merging**
