### PR TITLE
Add Code Climate Support

### PR DESCRIPTION
**Pull request by dylanapplegate**
**Description of the change**:
Ran codeclimate cli init in root of site to generate appropriate codeclimate and supporting files

**Reason for the change**:
Issue #48 

**Link to original source**:

### Checklist

Make sure all of these items are complete, or else the PR will be ineligible for a code review.

- [x] Code passes all existing [tests](https://github.com/sendgrid/nodemailer-sendgrid-transport/tree/master/test)
- [x] Any new functionality added includes new unit tests in [`test/test.js`](https://github.com/sendgrid/nodemailer-sendgrid-transport/tree/master/test/test.js)
- [x] Create or update example code to show the new functionality in action.
- [x] All code, branch, and git naming and style conventions are followed (see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodemailer-sendgrid-transport/blob/master/CONTRIBUTING.md#style-guidelines--naming-conventions))
- [x] Feature branch has been rebased off of the latest `master` branch. ( see [`CONTRIBUTING.md`](https://github.com/sendgrid/nodemailer-sendgrid-transport/blob/master/CONTRIBUTING.md#creating-a-pull-request) ).

If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by mbernier** [comment]
Oh damn, this is awesome!

**Comment by mbernier** [comment]
Thank you so much! We are going to get codeclimate set up to watch this repo now!

**Comment by thinkingserious** [comment]
Hello @deanbrophy,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@deanbrophy 
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
